# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3
# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   <<: *default
#   database: storage/production.sqlite3

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: FriendList_dev
  username: megagig
  password: password
  host: localhost
test:
  <<: *default
  database: Friendlist_test
  username: megagig
  password: password
  host: localhost
production:
  <<: *default
  database: FriendList_prod
  username: megagig
  password: password
  host: localhost
